name: Feature request
description: Suggest a new feature or workflow improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What limitation or frustration are you hitting?
      placeholder: It is hard to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Add a setting to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you tried?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, references, CLI examples, or anything else.
